### ISSUE TITLE
Default construction

### ISSUE THREAD

**Issue by mortenvp** [TartanLlama/function_ref#13]
Hi @TartanLlama 
Thanks for this nice implementation - we've been wanting to use this in our code base for a while, and yesterday we gave it a try. However, we quickly ran into a problem: The `function_ref` object is not default constructional. 

We use the `function_ref` objects as delegates, so often they are public members of the objects and we then later wire them together (like the includeos guys does here: https://youtu.be/QMb4RRFrY-o?t=1251).

What do you think about enabling default construction and having bool operator to check if initialized? I could make a pull-request if needed.

**Comment by dalle** [comment]
Latest revision of "function_ref: a non-owning reference to a Callable" / [p0792r4](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0792r4.html) does not have an empty state. Actually this was removed in r1.

Perhaps you need to combine `function_ref` with `optional` in order to achieve what your after.

But I'm thinking if you really are looking for a _non-owning_ reference to a Callable as your delegates may be invalidated after assignment. The following is an augmented example from the p0792r4 paper;

```
struct test
{
  function_ref<void()> f;
};

int main()
{
  test t;
  t.f = []{}; // temporary lambda lifetime ends after the semi-colon
  // ...
  t.f(); // undefined behavior
}
```

**Comment by mortenvp** [comment]
Hi @dalle,
Thanks for the link - I skimmed though it and I think it makes sense that `function_ref` would have reference semantics.. But would we also get a `function_ptr` - that would be super nice.
